kind: Deployment
apiVersion: apps/v1
metadata:
  name: prophet
  namespace: kube-admin
  labels:
    app: prophet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prophet
  template:
    metadata:
      labels:
        app: prophet
    spec:
      serviceAccountName: hulk
      containers:
        - name: prophet
          image: 'iyacontrol/prophet:v0.0.1'
          env:
            - name: 'PROPHET_IMAGE'
              value: ''
            - name: 'PROPHET_ACCOUNT'
              value: 'hulk'
          resources:
            limits:
              cpu: '0.5'
              memory: 0.5Gi
            requests:
              cpu: '0.5'
              memory: 0.5Gi
          imagePullPolicy: Always
